//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Compra
    {
        public int IdDetalleCompra { get; set; }
        public int IdCompra { get; set; }
        public int IdProductoBodega { get; set; }
        public decimal PrecioCompra { get; set; }
        public int Regalia { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Producto_Bodega Producto_Bodega { get; set; }
    }
}
