//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Farmacia_Veterinaria_Salud_AnimalEntities12 : DbContext
    {
        public Farmacia_Veterinaria_Salud_AnimalEntities12()
            : base("name=Farmacia_Veterinaria_Salud_AnimalEntities12")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bodega> Bodega { get; set; }
        public DbSet<Compra> Compra { get; set; }
        public DbSet<Configuracion> Configuracion { get; set; }
        public DbSet<Detalle_Compra> Detalle_Compra { get; set; }
        public DbSet<Detalle_Venta> Detalle_Venta { get; set; }
        public DbSet<Factura> Factura { get; set; }
        public DbSet<Laboratorio> Laboratorio { get; set; }
        public DbSet<Lote> Lote { get; set; }
        public DbSet<Presentacion> Presentacion { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Producto_Bodega> Producto_Bodega { get; set; }
        public DbSet<Proveedor> Proveedor { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tipo> Tipo { get; set; }
        public DbSet<Tipo_de_Pago> Tipo_de_Pago { get; set; }
        public DbSet<Unidad_Medida> Unidad_Medida { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Venta> Venta { get; set; }
    }
}
