//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_Bodega
    {
        public Producto_Bodega()
        {
            this.Detalle_Compra = new HashSet<Detalle_Compra>();
            this.Detalle_Venta = new HashSet<Detalle_Venta>();
        }
    
        public int IdProductoBodega { get; set; }
        public int IdProducto { get; set; }
        public int IdBodega { get; set; }
        public int IdUnidadMedida { get; set; }
        public int IdPresentacion { get; set; }
        public int IdLaboratorio { get; set; }
        public decimal PrecioCompra { get; set; }
        public decimal PrecioVenta { get; set; }
        public string Concentracion { get; set; }
        public string Adminisrtracion { get; set; }
        public int IdLote { get; set; }
        public int Existencia { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual ICollection<Detalle_Compra> Detalle_Compra { get; set; }
        public virtual ICollection<Detalle_Venta> Detalle_Venta { get; set; }
        public virtual Laboratorio Laboratorio { get; set; }
        public virtual Lote Lote { get; set; }
        public virtual Presentacion Presentacion { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Unidad_Medida Unidad_Medida { get; set; }
    }
}
