//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_de_Pago
    {
        public Tipo_de_Pago()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int IdPago { get; set; }
        public string Nombre { get; set; }
        public decimal Valor { get; set; }
    
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
